# Generated by Django 5.2.17 on 2026-09-19 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('review', models.TextField()),
                ('rating', models.PositiveIntegerField(default=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
