# Generated by Django 5.2.17 on 2026-09-19 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenancePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('features', models.TextField(help_text='Enter each feature on a new line')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
