# Generated by Django 5.2.17 on 2026-09-19 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(default='5-tips-to-keep-your-ac-running-efficiently', unique=True),
            preserve_default=False,
        ),
    ]
