# Generated by Django 5.2.17 on 2026-09-19 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_service_meta_description_service_meta_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicearea',
            name='meta_description',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='servicearea',
            name='meta_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='servicearea',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
