# Generated by Django 5.2.17 on 2026-09-19 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_servicearea_meta_description_servicearea_meta_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='core.service'),
        ),
    ]
