# Generated by Django 5.2.17 on 2026-09-22 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_service_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='dispatch_status',
            field=models.CharField(choices=[('not_assigned', 'Not Assigned'), ('assigned', 'Technician Assigned'), ('dispatched', 'Dispatched'), ('on_site', 'On Site'), ('completed', 'Completed')], default='not_assigned', max_length=20),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='estimated_aed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('quoted', 'Quoted'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='technician',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='urgency',
            field=models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Urgent'), ('emergency', 'Emergency 24/7')], default='normal', max_length=20),
        ),
    ]
