# Generated by Django 5.2.17 on 2026-09-22 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_quoterequest_dispatch_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancepackage',
            name='discount_percent',
            field=models.PositiveIntegerField(default=15, help_text='Discount percentage shown on website, e.g. 15'),
        ),
    ]
